table 'WTG ID'
	lineageTag: ff050a32-c9b4-4d7e-bbc2-5e09ad22bbce

	column 'WTG ID'
		dataType: string
		lineageTag: c52c0d84-cbf7-4dfe-9a10-76212904d845
		summarizeBy: none
		sourceColumn: WTG ID

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: d1b53cd3-0374-4b4b-8f52-af2605f1a245
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Dummy
		dataType: int64
		formatString: 0
		lineageTag: 79033484-2ff4-4df0-a16a-f9dc318f4f5a
		summarizeBy: sum
		sourceColumn: Dummy

		annotation SummarizationSetBy = Automatic

	partition 'WTG ID' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Z004Y62J\OneDrive - Siemens Energy\Attachments\Docs reports\ExportDocs-20260218_07-36.xlsx"), null, true),
				    Docs1 = Source{[Name="Docs"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Docs1,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",10),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"File", type text}, {"Contractor ID", type text}, {"D2 ID", type text}, {"Document No", type text}, {"Title", type text}, {"Revision", Int64.Type}, {"Discipline", type text}, {"Type", type text}, {"Doc. Nature", type text}, {"Status", type text}, {"Review Status", type text}, {"Contractual Date", type text}, {"Actual issue date", type text}, {"Required in Final Documentation?", type text}, {"Final Documentation Book", type text}, {"Section", type text}, {"Volume/Sub-section", type text}, {"Milestone ID", type text}, {"MWS Review?", type text}, {"CB Review?", type text}, {"Comments", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"File", "D2 ID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [Milestone ID] <> null and [Milestone ID] <> ""),
				    Title1 = #"Filtered Rows"[Title],
				    #"Converted to Table" = Table.FromList(Title1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Removed Duplicates" = Table.Distinct(#"Converted to Table"),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Removed Duplicates", "Text After Delimiter", each Text.AfterDelimiter([Column1], " ", 6), type text),
				    #"Trimmed Text" = Table.TransformColumns(#"Inserted Text After Delimiter",{{"Text After Delimiter", Text.Trim, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Trimmed Text",{{"Text After Delimiter", "WTG ID"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 1, 1, Int64.Type),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Index",{"Column1"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "Dummy", each 1),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Dummy", Int64.Type}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

